# Generated by Django 2.1.4 on 2018-12-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microlly', '0002_auto_20181129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
